int op_add(struct mipsstr *mips, byte rs, byte rt, byte rd);
struct mipsstr *print_add(struct mipsstr *mips, byte rs, byte rt, byte rd);
int op_addi(struct mipsstr *mips, byte rs, byte rt, halfword inm);
struct mipsstr *print_addi(struct mipsstr *mips, byte rs, byte rt, halfword inm);
int op_addiu(struct mipsstr *mips, byte rs, byte rt, halfword inm);
struct mipsstr *print_addiu(struct mipsstr *mips, byte rs, byte rt, halfword inm);
int op_addu(struct mipsstr *mips, byte rs, byte rt, byte rd);
struct mipsstr *print_addu(struct mipsstr *mips, byte rs, byte rt, byte rd);
int op_and(struct mipsstr *mips, byte rs, byte rt, byte rd);
struct mipsstr *print_and(struct mipsstr *mips, byte rs, byte rt, byte rd);
int op_andi(struct mipsstr *mips, byte rs, byte rt, halfword inm);
struct mipsstr *print_andi(struct mipsstr *mips, byte rs, byte rt, halfword inm);
int op_beq(struct mipsstr *mips, byte rs, byte rt, halfword inm);
struct mipsstr *print_beq(struct mipsstr *mips, byte rs, byte rt, halfword offset);
int op_bgez(struct mipsstr *mips, byte rs, halfword inm);
struct mipsstr *print_bgez(struct mipsstr *mips, byte rs, halfword offset);
int op_bgtz(struct mipsstr *mips, byte rs, halfword inm);
struct mipsstr *print_bgtz(struct mipsstr *mips, byte rs, halfword offset);
int op_blez(struct mipsstr *mips, byte rs, halfword inm);
struct mipsstr *print_blez(struct mipsstr *mips, byte rs, halfword offset);
int op_bltz(struct mipsstr *mips, byte rs, halfword inm);
struct mipsstr *print_bltz(struct mipsstr *mips, byte rs, halfword offset);
int op_bne(struct mipsstr *mips, byte rs, byte rt, halfword inm);
struct mipsstr *print_bne(struct mipsstr *mips, byte rs, byte rt, halfword inm);
int op_div(struct mipsstr *mips, byte rs, byte rt);
struct mipsstr *print_div(struct mipsstr *mips, byte rs, byte rt);
int op_j(struct mipsstr *mips, word idx);
struct mipsstr *print_j(struct mipsstr *mips, word idx);
int op_jal(struct mipsstr *mips, word idx);
struct mipsstr *print_jal(struct mipsstr *mips, word idx);
int op_jalr(struct mipsstr *mips, byte rs, byte rd);
struct mipsstr *print_jalr(struct mipsstr *mips, byte rs, byte rd);
int op_jr(struct mipsstr *mips, byte rs);
struct mipsstr *print_jr(struct mipsstr *mips, byte rs);
int op_lb(struct mipsstr *mips, byte base, byte rt, halfword offset);
struct mipsstr *print_lb(struct mipsstr *mips, byte base, byte rt, halfword offset);
int op_lbu(struct mipsstr *mips, byte base, byte rt, halfword offset);
struct mipsstr *print_lbu(struct mipsstr *mips, byte base, byte rt, halfword offset);
int op_lui(struct mipsstr *mips, byte rt, halfword inmediate);
struct mipsstr *print_lui(struct mipsstr *mips, byte rt, halfword inmediate);
int op_lw(struct mipsstr *mips, byte base, byte rt, halfword inmediate);
struct mipsstr *print_lw(struct mipsstr *mips, byte base, byte rt, halfword inmediate);
int op_mfhi(struct mipsstr *mips, byte rd);
struct mipsstr *print_mfhi(struct mipsstr *mips, byte rd);
int op_mflo(struct mipsstr *mips, byte rd);
struct mipsstr *print_mflo(struct mipsstr *mips, byte rd);
int op_mult(struct mipsstr *mips, byte rs, byte rt);
struct mipsstr *print_mult(struct mipsstr *mips, byte rs, byte rt);
int op_nop(struct mipsstr *mips);
struct mipsstr *print_nop(struct mipsstr *mips);
int op_or(struct mipsstr *mips, byte rs, byte rt, byte rd);
struct mipsstr *print_or(struct mipsstr *mips, byte rs, byte rt, byte rd);
int op_ori(struct mipsstr *mips, byte rs, byte rt, halfword inm);
struct mipsstr *print_ori(struct mipsstr *mips, byte rs, byte rt, halfword inm);
int op_sb(struct mipsstr *mips, byte base, byte rt, halfword offset);
struct mipsstr *print_sb(struct mipsstr *mips, byte base, byte rt, halfword offset);
int op_seb(struct mipsstr *mips, byte rt, byte rd);
struct mipsstr *print_seb(struct mipsstr *mips, byte rt, byte rd);
int op_sll(struct mipsstr *mips, byte rt, byte rd, byte sa);
struct mipsstr *print_sll(struct mipsstr *mips, byte rt, byte rd, byte sa);
int op_slt(struct mipsstr *mips, byte rs, byte rt, byte rd);
struct mipsstr *print_slt(struct mipsstr *mips, byte rs, byte rt, byte rd);
int op_slti(struct mipsstr *mips, byte rs, byte rt, halfword inm);
struct mipsstr *print_slti(struct mipsstr *mips, byte rs, byte rt, halfword inm);
int op_sltu(struct mipsstr *mips, byte rs, byte rt, byte rd);
struct mipsstr *print_sltu(struct mipsstr *mips, byte rs, byte rt, byte rd);
int op_sltiu (struct mipsstr *mips, byte rs, byte rt, halfword inm);
struct mipsstr *print_sltiu(struct mipsstr *mips, byte rs, byte rt, halfword inm);
int op_sra(struct mipsstr *mips, byte rt, byte rd, byte sa);
struct mipsstr *print_sra(struct mipsstr *mips, byte rt, byte rd, byte sa);
int op_srl(struct mipsstr *mips, byte rt, byte rd, byte sa);
struct mipsstr *print_srl(struct mipsstr *mips, byte rt, byte rd, byte sa);
int op_sub(struct mipsstr *mips, byte rs, byte rt, byte rd);
struct mipsstr *print_sub(struct mipsstr *mips, byte rs, byte rt, byte rd);
int op_subu(struct mipsstr *mips, byte rs, byte rt, byte rd);
struct mipsstr *print_subu(struct mipsstr *mips, byte rs, byte rt, byte rd);
int op_sw(struct mipsstr *mips, byte base, byte rt, halfword offset);
struct mipsstr *print_sw(struct mipsstr *mips, byte base, byte rt, halfword offset);
int op_xor(struct mipsstr *mips, byte rs, byte rt, byte rd);
struct mipsstr *print_xor(struct mipsstr *mips, byte rs, byte rt, byte rd);
int op_syscall(struct mipsstr *mips);
struct mipsstr *print_syscall(struct mipsstr *mips);
