int op_add(struct ptype *mips, byte rs, byte rt, byte rd);
struct ptype *print_add(struct ptype *mips, byte rs, byte rt, byte rd);
int op_addi(struct ptype *mips, byte rs, byte rt, halfword inm);
struct ptype *print_addi(struct ptype *mips, byte rs, byte rt, halfword inm);
int op_addiu(struct ptype *mips, byte rs, byte rt, halfword inm);
struct ptype *print_addiu(struct ptype *mips, byte rs, byte rt, halfword inm);
int op_addu(struct ptype *mips, byte rs, byte rt, byte rd);
struct ptype *print_addu(struct ptype *mips, byte rs, byte rt, byte rd);
int op_and(struct ptype *mips, byte rs, byte rt, byte rd);
struct ptype *print_and(struct ptype *mips, byte rs, byte rt, byte rd);
int op_andi(struct ptype *mips, byte rs, byte rt, halfword inm);
struct ptype *print_andi(struct ptype *mips, byte rs, byte rt, halfword inm);
int op_beq(struct ptype *mips, byte rs, byte rt, halfword inm);
struct ptype *print_beq(struct ptype *mips, byte rs, byte rt, halfword offset);
int op_bgez(struct ptype *mips, byte rs, halfword inm);
struct ptype *print_bgez(struct ptype *mips, byte rs, halfword offset);
int op_bgtz(struct ptype *mips, byte rs, halfword inm);
struct ptype *print_bgtz(struct ptype *mips, byte rs, halfword offset);
int op_blez(struct ptype *mips, byte rs, halfword inm);
struct ptype *print_blez(struct ptype *mips, byte rs, halfword offset);
int op_bltz(struct ptype *mips, byte rs, halfword inm);
struct ptype *print_bltz(struct ptype *mips, byte rs, halfword offset);
int op_bne(struct ptype *mips, byte rs, byte rt, halfword inm);
struct ptype *print_bne(struct ptype *mips, byte rs, byte rt, halfword inm);
int op_div(struct ptype *mips, byte rs, byte rt);
struct ptype *print_div(struct ptype *mips, byte rs, byte rt);
int op_j(struct ptype *mips, word idx);
struct ptype *print_j(struct ptype *mips, word idx);
int op_jal(struct ptype *mips, word idx);
struct ptype *print_jal(struct ptype *mips, word idx);
int op_jalr(struct ptype *mips, byte rs, byte rd);
struct ptype *print_jalr(struct ptype *mips, byte rs, byte rd);
int op_jr(struct ptype *mips, byte rs);
struct ptype *print_jr(struct ptype *mips, byte rs);
int op_lb(struct ptype *mips, byte base, byte rt, halfword offset);
struct ptype *print_lb(struct ptype *mips, byte base, byte rt, halfword offset);
int op_lbu(struct ptype *mips, byte base, byte rt, halfword offset);
struct ptype *print_lbu(struct ptype *mips, byte base, byte rt, halfword offset);
int op_lui(struct ptype *mips, byte rt, halfword inmediate);
struct ptype *print_lui(struct ptype *mips, byte rt, halfword inmediate);
int op_lw(struct ptype *mips, byte base, byte rt, halfword inmediate);
struct ptype *print_lw(struct ptype *mips, byte base, byte rt, halfword inmediate);
int op_mfhi(struct ptype *mips, byte rd);
struct ptype *print_mfhi(struct ptype *mips, byte rd);
int op_mflo(struct ptype *mips, byte rd);
struct ptype *print_mflo(struct ptype *mips, byte rd);
int op_mult(struct ptype *mips, byte rs, byte rt);
struct ptype *print_mult(struct ptype *mips, byte rs, byte rt);
int op_nop(struct ptype *mips);
struct ptype *print_nop(struct ptype *mips);
int op_or(struct ptype *mips, byte rs, byte rt, byte rd);
struct ptype *print_or(struct ptype *mips, byte rs, byte rt, byte rd);
int op_ori(struct ptype *mips, byte rs, byte rt, halfword inm);
struct ptype *print_ori(struct ptype *mips, byte rs, byte rt, halfword inm);
int op_sb(struct ptype *mips, byte base, byte rt, halfword offset);
struct ptype *print_sb(struct ptype *mips, byte base, byte rt, halfword offset);
int op_seb(struct ptype *mips, byte rt, byte rd);
struct ptype *print_seb(struct ptype *mips, byte rt, byte rd);
int op_sll(struct ptype *mips, byte rt, byte rd, byte sa);
struct ptype *print_sll(struct ptype *mips, byte rt, byte rd, byte sa);
int op_slt(struct ptype *mips, byte rs, byte rt, byte rd);
struct ptype *print_slt(struct ptype *mips, byte rs, byte rt, byte rd);
int op_slti(struct ptype *mips, byte rs, byte rt, halfword inm);
struct ptype *print_slti(struct ptype *mips, byte rs, byte rt, halfword inm);
int op_sltu(struct ptype *mips, byte rs, byte rt, byte rd);
struct ptype *print_sltu(struct ptype *mips, byte rs, byte rt, byte rd);
int op_sltiu (struct ptype *mips, byte rs, byte rt, halfword inm);
struct ptype *print_sltiu(struct ptype *mips, byte rs, byte rt, halfword inm);
int op_sra(struct ptype *mips, byte rt, byte rd, byte sa);
struct ptype *print_sra(struct ptype *mips, byte rt, byte rd, byte sa);
int op_srl(struct ptype *mips, byte rt, byte rd, byte sa);
struct ptype *print_srl(struct ptype *mips, byte rt, byte rd, byte sa);
int op_sub(struct ptype *mips, byte rs, byte rt, byte rd);
struct ptype *print_sub(struct ptype *mips, byte rs, byte rt, byte rd);
int op_subu(struct ptype *mips, byte rs, byte rt, byte rd);
struct ptype *print_subu(struct ptype *mips, byte rs, byte rt, byte rd);
int op_sw(struct ptype *mips, byte base, byte rt, halfword offset);
struct ptype *print_sw(struct ptype *mips, byte base, byte rt, halfword offset);
int op_xor(struct ptype *mips, byte rs, byte rt, byte rd);
struct ptype *print_xor(struct ptype *mips, byte rs, byte rt, byte rd);